Refine the maze environments
aykut-tri/quasistatic_simulator pull request #4
Opened 2023-01-12 23:56 UTC by aykut-tri

Removes the gravity and the ground collision as well as shortens the wall for the iiwa maze example

2023-01-19 19:18 UTC, JoseBarreiros-TRI commented on models/iiwa_sphere_collision_maze0.yml
>  directives:
for consistency, this should be name iiwa_sphere_collision_maze0_no_ground.yml

2023-01-19 19:20 UTC, JoseBarreiros-TRI commented on models/q_sys/iiwa_box_maze_xy0.yml
>      file: package://quasistatic_simulator/box_for_maze_xy_rotation.sdf
for consistency, this should be named iiwa_box_maze_xy0_no_ground.

2023-01-19 19:20 UTC, JoseBarreiros-TRI requested changes
just a few nits.

2023-01-24 01:02 UTC, aykut-tri commented on models/iiwa_sphere_collision_maze0.yml
>  directives:
done, thanks

2023-01-24 01:03 UTC, aykut-tri commented on models/q_sys/iiwa_box_maze_xy0.yml
>      file: package://quasistatic_simulator/box_for_maze_xy_rotation.sdf
done, thanks

2023-01-24 03:31 UTC, merged